### ISSUE TITLE
Unable to compile: CL/opencl.h not found

### ISSUE THREAD

**Issue by avinashkarkada** [DeltaGroupNJUPT/Vina-GPU#35]
I am getting the following error when I try to run Vina-GPU:
`./Vina-GPU: error while loading shared libraries: libboost_program_options.so.1.81.0: cannot open shared object file: No such file or directory`

**Comment by Glinttsd** [comment]
Hi, errors like `error while loading shared libraries` are common errors to many softwares. The problem seems to be not setting boost library well. Maybe you can check [this](https://stackoverflow.com/questions/4581305/error-while-loading-shared-libraries-libboost-system-so-1-45-0-cannot-open-sha) out.
